name: tagpr-on-label
on:
  pull_request:
    types: [labeled, unlabeled]
    paths:
      - 'CHANGELOG.md'
    branches:
      - main

jobs:
  tagpr-on-label:
    if: startsWith(github.head_ref, 'tagpr-from-') && (github.event.label.name == 'tagpr:minor' || github.event.label.name == 'tagpr:major')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.AMEGO_RELEASES_APP_ID }}
          private-key: ${{ secrets.AMEGO_RELEASES_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: main
      - name: Setup Git credentials
        run: |
          git config --global user.name 'amego-releases[bot]'
          git config --global user.email '183133136+amego-releases[bot]@users.noreply.github.com>'
      - uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
